FROM node:24-alpine AS base

RUN apk update && apk add --no-cache libc6-compat postgresql-client
RUN npm install -g pnpm@11.9.0

FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm dlx turbo prune worker --docker

FROM base AS runner
WORKDIR /app

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN pnpm install --frozen-lockfile

COPY --from=builder /app/out/full/ .

ENV NODE_ENV=development

CMD ["pnpm", "dev"]
