import { BackupFlags, RestoreFlags } from "@/types";

export const DEFAULT_BACKUP_FLAGS: BackupFlags = {
  format: "custom",
  compress: true,
  dataOnly: false,
  schemaOnly: false,
  clean: false,
  create: false,
  ifExists: false,
  noOwner: false,
  noPrivileges: false,
  verbose: true,
  jobs: 1,
  inserts: false,
  excludeSchemas: [],
  includeSchemas: [],
  excludeTables: [],
  includeTables: [],
  excludeTableData: [],
};

export const DEFAULT_RESTORE_FLAGS: RestoreFlags = {
  format: "custom",
  dataOnly: false,
  schemaOnly: false,
  clean: false,
  create: false,
  noOwner: false,
  noPrivileges: false,
  disableTriggers: false,
  verbose: true,
  jobs: 1,
  singleTransaction: true,
  exitOnError: true,
  ifExists: false,
  excludeSchemas: [],
  includeSchemas: [],
  includeTables: [],
};
