FROM node:24-alpine

RUN apk update && apk add --no-cache libc6-compat postgresql-client openssl

WORKDIR /app

RUN corepack enable pnpm 

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN sed -i 's/\r$//' ./entrypoint.sh && chmod +x ./entrypoint.sh

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]

CMD ["pnpm", "dev"]