#!/bin/sh
# pgbr installer — fetches compose.prod.yaml, generates secrets into .env, starts the stack.
#   curl -fsSL https://raw.githubusercontent.com/darseen/pgbr/main/scripts/install.sh | sh
# Re-run it in an existing install to upgrade: secrets and edits are preserved.
set -eu

REPO=${PGBR_REPO:-darseen/pgbr}
REF=${PGBR_REF:-main}
RAW=${PGBR_RAW:-https://raw.githubusercontent.com/$REPO/$REF}
START=1

# PGBR_REF=2.4.1 should pin the images too, not just the compose file.
case "$REF" in
  [0-9]*.[0-9]*) PGBR_VERSION=${PGBR_VERSION:-$REF} ;;
esac

for arg in "$@"; do
  case "$arg" in
    --no-start) START=0 ;;
    --dir=*) PGBR_DIR=${arg#--dir=} ;;
    -h | --help)
      echo "usage: install.sh [--dir=PATH] [--no-start]"
      echo "env: BASE_URL, PGBR_DIR, PGBR_PORT, PGBR_VERSION, PGBR_REF, PGBR_REPO"
      exit 0
      ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

info() { printf '\033[36m[pgbr]\033[0m %s\n' "$1"; }
warn() { printf '\033[33m[pgbr]\033[0m %s\n' "$1" >&2; }
die() { printf '\033[31m[pgbr]\033[0m %s\n' "$1" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1; }

fetch() {
  if need curl; then curl -fsSL "$1"
  elif need wget; then wget -qO- "$1"
  else die "need curl or wget to download files"; fi
}

rand_b64() {
  if need openssl; then openssl rand -base64 32
  else head -c 32 /dev/urandom | base64; fi | tr -d '\n'
}

# Hex, not base64: this one goes inside DATABASE_URL, where + / = would break parsing.
rand_hex() {
  if need openssl; then openssl rand -hex 24
  else head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi | tr -d '\n'
}

# -r /dev/tty is not enough: it exists but fails to open with no controlling
# terminal. Subshell so that failure is a status, not a fatal redirect error.
has_tty() { ( : >/dev/tty ) 2>/dev/null; }

ask() {
  _q=$1 _default=$2 _answer=""
  if has_tty; then
    printf '\033[36m[pgbr]\033[0m %s [%s]: ' "$_q" "$_default" >/dev/tty
    read -r _answer </dev/tty || _answer=""
  fi
  [ -n "$_answer" ] || _answer=$_default
  printf '%s' "$_answer"
}

env_get() {
  [ -f .env ] || return 0
  sed -n "s/^[[:space:]]*$1=//p" .env | head -n1
}

env_put() {
  if [ -n "$(env_get "$1")" ]; then return 0; fi
  printf '%s=%s\n' "$1" "$2" >>.env
}

need docker || die "docker is not installed — see https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is required (docker compose version)"
docker info >/dev/null 2>&1 || die "cannot reach the docker daemon — is it running, and is your user in the docker group?"

if [ -z "${PGBR_DIR:-}" ]; then
  if [ -f .env ] && [ -f compose.prod.yaml ]; then PGBR_DIR=$PWD; else PGBR_DIR=$PWD/pgbr; fi
fi
mkdir -p "$PGBR_DIR"
cd "$PGBR_DIR"

if [ -f .env ]; then
  info "existing install found in $PGBR_DIR — keeping .env, updating compose.prod.yaml"
else
  info "installing into $PGBR_DIR"
fi

info "fetching compose.prod.yaml"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT INT TERM
fetch "$RAW/compose.prod.yaml" >"$tmp" || die "could not download compose.prod.yaml from $RAW"
[ -s "$tmp" ] || die "downloaded compose.prod.yaml is empty"
if [ -f compose.prod.yaml ] && ! cmp -s "$tmp" compose.prod.yaml; then
  cp compose.prod.yaml compose.prod.yaml.bak
  info "previous compose.prod.yaml saved as compose.prod.yaml.bak"
fi
cat "$tmp" >compose.prod.yaml

base_url=${BASE_URL:-$(env_get BASE_URL)}
if [ -z "$base_url" ]; then
  base_url=$(ask "URL you will open pgbr on" "http://localhost:3000")
  has_tty || warn "no terminal to prompt on — defaulting BASE_URL to $base_url; edit .env if that is not the URL you open"
fi

if [ ! -f .env ]; then
  umask 077
  cat >.env <<EOF
# Generated by scripts/install.sh. Keep ENCRYPTION_KEY backed up somewhere else:
# it decrypts your saved connection strings, and there is no recovery without it.

PGBR_VERSION=${PGBR_VERSION:-latest}

ENCRYPTION_KEY=$(rand_b64)
AUTH_SECRET=$(rand_b64)
POSTGRES_PASSWORD=$(rand_hex)
POSTGRES_USER=pgbr
POSTGRES_DB=pgbr

BASE_URL=$base_url

# Set PGBR_BIND_ADDR=127.0.0.1 when a reverse proxy fronts the dashboard.
PGBR_BIND_ADDR=${PGBR_BIND_ADDR:-0.0.0.0}
PGBR_PORT=${PGBR_PORT:-3000}

WORKER_CONCURRENCY=5

# Object storage. Defaults target the bundled SeaweedFS; point these at S3, R2
# or Backblaze for real durability and drop the seaweedfs service.
STORAGE_ENDPOINT=http://seaweedfs:8333
STORAGE_REGION=us-east-1
STORAGE_BUCKET=pgbr
STORAGE_ACCESS_KEY_ID=pgbr
STORAGE_SECRET_ACCESS_KEY=pgbrsecret
STORAGE_FORCE_PATH_STYLE=true
EOF
  info "wrote .env with freshly generated secrets"
else
  # Only fill gaps — never touch a value the user already has.
  env_put PGBR_VERSION "${PGBR_VERSION:-latest}"
  env_put ENCRYPTION_KEY "$(rand_b64)"
  env_put AUTH_SECRET "$(rand_b64)"
  env_put POSTGRES_PASSWORD "$(rand_hex)"
  env_put BASE_URL "$base_url"
fi
chmod 600 .env 2>/dev/null || true

if [ "$START" -eq 0 ]; then
  info "skipping start — run: docker compose -f compose.prod.yaml up -d"
  exit 0
fi

info "pulling images"
docker compose -f compose.prod.yaml pull --quiet

info "starting pgbr"
docker compose -f compose.prod.yaml up -d --remove-orphans

port=$(env_get PGBR_PORT)
[ -n "$port" ] || port=3000
url=$(env_get BASE_URL)

info "waiting for the dashboard to become healthy (migrations run on first boot)"
i=0
while [ "$i" -lt 90 ]; do
  state=$(docker compose -f compose.prod.yaml ps --format '{{.Health}}' dashboard 2>/dev/null || true)
  case "$state" in
    healthy) break ;;
    unhealthy) die "dashboard is unhealthy — docker compose -f compose.prod.yaml logs dashboard" ;;
  esac
  i=$((i + 1))
  sleep 2
done

if [ "$i" -ge 90 ]; then
  warn "dashboard did not report healthy in time — check: docker compose -f compose.prod.yaml logs -f dashboard"
else
  info "pgbr is up"
fi

echo
info "open $url and register — the first account becomes the admin, then sign-up closes"
info "listening on port $port  ·  files in $PGBR_DIR  ·  secrets in $PGBR_DIR/.env"
info "back up ENCRYPTION_KEY now; losing it makes every saved connection unreadable"
