FROM node:24-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable pnpm

FROM base AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN pnpm dlx turbo prune dashboard --docker

FROM base AS installer
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN pnpm install --frozen-lockfile

COPY --from=builder /app/out/full/ .
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm turbo build --filter=dashboard...

RUN pnpm deploy --filter=@repo/db --prod --legacy /prod/db

FROM base AS runner

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    postgresql-common \
    && /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y \
    && apt-get install -y --no-install-recommends \
    openssl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY --from=installer /app/apps/dashboard/.next/standalone ./
COPY --from=installer /app/apps/dashboard/.next/static ./apps/dashboard/.next/static

COPY --from=installer /app/apps/dashboard/entrypoint.sh ./apps/dashboard/entrypoint.sh
COPY --from=installer /prod/db ./packages/db

RUN chmod +x ./apps/dashboard/entrypoint.sh

EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME="0.0.0.0"

ENTRYPOINT ["./apps/dashboard/entrypoint.sh"]
CMD ["node", "apps/dashboard/server.js"]