FROM node:24-alpine AS base

RUN apk update && apk add --no-cache libc6-compat postgresql-client openssl
RUN npm install -g pnpm@11.9.0

FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm dlx turbo prune dashboard --docker

FROM base AS runner
WORKDIR /app

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN pnpm install --frozen-lockfile

COPY --from=builder /app/out/full/ .

RUN sed -i 's/\r$//' ./apps/dashboard/entrypoint.sh && chmod +x ./apps/dashboard/entrypoint.sh

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

ENTRYPOINT ["./apps/dashboard/entrypoint.sh"]
CMD ["pnpm", "dev"]